name: 'Hello World'
description: 'Greet someone'

inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
  shell:  # id of input
    description: 'Use shell'
    required: false
    default: ''


outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-number }}


runs:
  using: "composite"
  steps:

    - name: inputs.who-to-greet
      id: who
      run: echo Hello ${{ inputs.who-to-greet }}.
      shell: bash

    - name: inputs.shell
      id: shell
      run: echo Shell is ${{ inputs.shell }}.
      shell: ${{ inputs.shell }}



    - name: random-number-generator
      id: random-number-generator
      run: echo "random-number=$(echo $RANDOM)" >> $GITHUB_OUTPUT
      shell: bash

    - name: is-Linux
      id: is-Linux
      if: runner.os == 'Linux'
      run: |
       sudo locale-gen sk_SK.utf8
       sudo update-locale LANG=sk_SK.utf8
       sudo timedatectl set-timezone Europe/Bratislava
       exit
       chmod +x ${{ github.action_path }}/goodbye.sh
       ${{ github.action_path }}/goodbye.sh
      shell: ${{ inputs.shell }}

    - name: is-macOS
      id: is-macOS
      if: runner.os == 'macOS'
      run: |
       echo ${{ runner.os }}
       sudo systemsetup -settimezone Europe/Bratislava
       sudo systemsetup -gettimezone
      shell: ${{ inputs.shell }}

    - name: is-Windows
      id: is-Windows
      if: runner.os == 'Windows' && inputs.shell != 'cmd'
      run: |
       echo ${{ runner.os }}
       Set-WinSystemLocale -SystemLocale sk-SK
       Set-Culture sk-SK
       Set-TimeZone -Id "Central Europe Standard Time"
       Get-TimeZone
       Get-Date -UFormat "%A %m/%d/%Y %R %Z"
      shell: ${{ inputs.shell }}

    - name: is-Windows-cmd
      id: is-Windows-cmd
      if: inputs.shell == 'cmd'
      run: |
        tzutil /s "Europe Standard Time"
        tzutil /g
      shell: ${{ inputs.shell }}