name: 'Hello World'
description: 'Greet someone'

inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
  shell:  # id of input
    description: 'Use shell'
    required: false
    default: ''
  locale:  # id of input
    description: 'Use locale'
    required: false
    default: ''
  timezone:  # id of input
    description: 'Use timezone'
    required: false
    default: ''


outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-number }}
  inputs-outputs:
    description: "inputs-outputs"
    value: ${{ steps.inputs-outputs.outputs.inputs-outputs }}

runs:
  using: "composite"
  steps:

    - name: inputs.who-to-greet
      id: who
      run: echo Hello ${{ inputs.who-to-greet }}.
      shell: bash

    - name: inputs.shell
      id: shell
      run: echo Shell is ${{ inputs.shell }}.
      shell: ${{ inputs.shell }}

    - name: inputs.locale
      id: shelocalell
      run: echo Locale is ${{ inputs.locale }}.
      shell: ${{ inputs.shell }}

    - name: inputs.timezone
      id: timezone
      run: echo Timezone is ${{ inputs.timezone }}.
      shell: ${{ inputs.shell }}

    - name: random-number-generator
      id: random-number-generator
      run: echo "random-number=$(echo $RANDOM)" >> $GITHUB_OUTPUT
      shell: bash

    - name: inputs-outputs
      id: inputs-outputs
      run: echo "inputs-outputs=$(echo ${{runner.os}} - ${{inputs.shell}} - ${{inputs.locale}} - ${{inputs.timezone}} )" >> $GITHUB_OUTPUT
      shell: bash


    - name: is-Linux
      id: is-Linux
      if: runner.os == 'Linux'
      run: |
       sudo locale-gen ${{ inputs.locale }}
       sudo update-locale LANG=${{ inputs.locale }}
       sudo timedatectl set-timezone ${{ inputs.timezone }}
       exit
       chmod +x ${{ github.action_path }}/goodbye.sh
       ${{ github.action_path }}/goodbye.sh
      shell: ${{ inputs.shell }}

    - name: is-macOS
      id: is-macOS
      if: runner.os == 'macOS'
      run: |
       echo ${{ runner.os }}
       sudo systemsetup -settimezone ${{ inputs.timezone }}
       sudo systemsetup -gettimezone
       exit
       chmod +x ${{ github.action_path }}/goodbye.sh
       ${{ github.action_path }}/goodbye.sh
      shell: ${{ inputs.shell }}

    - name: is-Windows
      id: is-Windows
      if: runner.os == 'Windows' && inputs.shell != 'cmd'
      run: |
       echo ${{ runner.os }}
       Set-WinSystemLocale -SystemLocale ${{ inputs.locale }}
       Set-Culture ${{ inputs.locale }}
       Set-TimeZone -Id "${{ inputs.timezone }}"
       Get-TimeZone
       Get-Date -UFormat "%A %m/%d/%Y %R %Z"
      shell: ${{ inputs.shell }}

    - name: is-Windows-cmd
      id: is-Windows-cmd
      if: inputs.shell == 'cmd'
      run: |
        tzutil /s "${{ inputs.timezone }}"
        tzutil /g
      shell: ${{ inputs.shell }}