name: 'shell-x'
description: 'localized github runners'
author: "milankomaj"
branding:
  icon: "x-square"
  color: "green"

inputs:
  actor:  # id of input
    description: 'Who to greet'
    required: false
    default: ${{ github.actor }}
  shell:  # id of input
    description: 'Use shell'
    required: false
    default: ""
  locale:  # id of input
    description: 'Use locale'
    required: false
    default: ""
  timezone:  # id of input
    description: 'Use timezone'
    required: false
    default: ""
  comand:  # id of input
    description: 'Use comand'
    required: false
    default: ""


outputs:
  inputs-outputs:
    description: "inputs-outputs"
    value: "${{ steps.inputs-outputs.outputs.inputs-outputs }}"
  shell-outputs:
    description: "shell-outputs"
    value: "${{ steps.shell-outputs.outputs.shell-outputs }}"



runs:
  using: "composite"
  steps:

    - name: inputs exists
      id: exists
      if: inputs.shell == '' && inputs.locale == '' && inputs.timezone == ''
      run: |
       echo "::warning::Hey ${{ inputs.actor }}, add some inputs"
       exit
      shell: bash

    - name: inputs values
      id: values
      run: |
        echo "::group:: INPUTS"
        echo "Actor: ${{ inputs.actor }}"
        echo "Shell: ${{ inputs.shell }}"
        echo "Locale: ${{ inputs.locale }}"
        echo "Timezone: ${{ inputs.timezone }}"
        echo "Comand: ${{ inputs.comand }}"
        echo "::endgroup::"
      shell: bash

    - name: inputs-outputs
      id: inputs-outputs
      run: echo -n "inputs-outputs=${{runner.os}} - ${{inputs.shell}} - ${{inputs.locale}} - ${{inputs.timezone}}" >> $GITHUB_OUTPUT
      shell: bash

    - name: shell-outputs
      id: shell-outputs
      if: inputs.shell != ''
      run: echo -n "shell-outputs=${{inputs.shell}}" >> $GITHUB_OUTPUT
      shell: bash

    - name: comand-outputs
      id: comand-outputs
      if: inputs.comand != ''
      run: echo -n "comand-outputs=${{inputs.comand}}" >> $GITHUB_OUTPUT
      shell: bash

    - name: is-Linux
      id: is-Linux
      if: runner.os == 'Linux'  && inputs.locale != '' && inputs.timezone != '' || runner.os == 'Linux'  && inputs.locale != '' && inputs.timezone != '' && inputs.shell == 'pwsh' || runner.os == 'Linux'  && inputs.locale != '' && inputs.timezone != '' && inputs.shell == 'bash' || runner.os == 'Linux' && inputs.shell != ''  && inputs.timezone != '' && inputs.shell == 'pwsh' || runner.os == 'Linux'  && inputs.locale != '' && inputs.timezone != '' && inputs.shell == 'sh'
      run: |
       echo "::group:: EXECUTING SHELL COMANDS"
       sudo locale-gen ${{ inputs.locale }}
       sudo update-locale LANG=${{ inputs.locale }}
       sudo timedatectl set-timezone ${{ inputs.timezone }}
       echo "LANG=$(echo ${{ inputs.locale }})" >> $GITHUB_ENV
       echo "::endgroup::"
      shell: ${{ inputs.shell }}

    - name: is-macOS
      id: is-macOS
      if: runner.os == 'macOS' && inputs.locale != '' && inputs.timezone != '' || runner.os == 'macOS'  && inputs.locale != '' && inputs.timezone != '' && inputs.shell == 'sh' || runner.os == 'macOS'  && inputs.locale != '' && inputs.timezone != '' && inputs.shell == 'bash'
      run: |
       echo "::group:: EXECUTING SHELL COMANDS"
       sudo systemsetup -settimezone ${{ inputs.timezone }} 2>/dev/null
       echo "export LANG=$(echo ${{ inputs.locale }})" >> ~/.bashrc
       echo "export LC_ALL=$(echo ${{ inputs.locale }})" >> ~/.bashrc
       echo "LANG=$(echo ${{ inputs.locale }})" >> $GITHUB_ENV
       echo "LC_ALL=$(echo ${{ inputs.locale }})" >> $GITHUB_ENV
       echo "::endgroup::"
      shell: ${{ inputs.shell }}

    - name: is-macOS-not-pwsh
      id: is-macOS-not-pwsh
      if: runner.os == 'macOS' && inputs.shell != 'pwsh'
      run: |
        source ~/.bashrc
      shell: ${{ inputs.shell }}

    - name: is-Windows
      id: is-Windows
      if: runner.os == 'Windows' && inputs.shell != 'cmd'  && inputs.locale != '' && inputs.timezone != '' || runner.os == 'Windows' && inputs.shell != 'cmd'  && inputs.locale != '' && inputs.timezone != ''  && inputs.shell == 'powershell' || runner.os == 'Windows' && inputs.shell != 'cmd' && inputs.locale != '' && inputs.timezone != ''  && inputs.shell == 'pwsh'
      run: |
       echo "::group:: EXECUTING SHELL COMANDS"
       Set-WinSystemLocale ${{ inputs.locale }}
       Set-WinSystemLocale -SystemLocale ${{ inputs.locale }}
       Set-Culture ${{ inputs.locale }}
       Set-Culture -CultureInfo ${{ inputs.locale }}
       Set-TimeZone -Id "${{ inputs.timezone }}"
       echo "::endgroup::"
      shell: ${{ inputs.shell }}

    - name: is-Windows-cmd
      id: is-Windows-cmd
      if: inputs.shell == 'cmd' && inputs.timezone != ''
      run: |
        echo "::group:: EXECUTING SHELL COMANDS"
        tzutil /s "${{ inputs.timezone }}"
        echo "::endgroup::"
      shell: ${{ inputs.shell }}

    - name: is-run-comand
      id: is-run-comand
      if: inputs.comand != '' && inputs.shell != ''
      run: |
        echo "::group:: RUN ${{ inputs.comand }}"
        ${{ inputs.comand }}
        echo "::endgroup::"
      shell: ${{ inputs.shell }}
