name: 'Hello World'
description: 'Greet someone'

inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: World
  shell:  # id of input
    description: 'Use shell'
    required: false
    default: ""
  locale:  # id of input
    description: 'Use locale'
    required: false
    default: ""
  timezone:  # id of input
    description: 'Use timezone'
    required: false
    default: ""
  neofetch:  # id of input
    description: 'Use neofetch'
    required: false
    default: 'false'
    type: boolean
  comand:  # id of input
    description: 'Use comand'
    required: false
    default: ""


outputs:
  random-number:
    description: "Random number"
    value: "${{ steps.random-number-generator.outputs.random-number }}"
  inputs-outputs:
    description: "inputs-outputs"
    value: "${{ steps.inputs-outputs.outputs.inputs-outputs }}"
  shell-outputs:
    description: "shell-outputs"
    value: "${{ steps.shell-outputs.outputs.shell-outputs }}"
  comand-outputs:
    description: "comand-outputs"
    value: "${{ steps.comand-outputs.outputs.comand-outputs }}"


runs:
  using: "composite"
  steps:

    - name: inputs.neofetch
      id: neo
      run: echo "Neofetch is ${{ inputs.neofetch }}."
      shell: bash

    - name: inputs.who-to-greet
      id: who
      run: echo "Hello ${{ inputs.who-to-greet }}."
      shell: bash

    - name: inputs.shell
      id: shell
      run: |
       echo "Shell is ${{ inputs.shell }}."
      shell: bash

    - name: inputs.locale
      id: locale
      run: |
       echo "Locale is ${{ inputs.locale }}."
       echo "LANG=$(echo ${{ inputs.locale }})" >> $GITHUB_ENV
      shell: bash

    - name: inputs.timezone
      id: timezone
      run: echo "Timezone is ${{ inputs.timezone }}."
      shell: bash

    - name: random-number-generator
      id: random-number-generator
      run: echo "random-number=$(echo $RANDOM)" >> $GITHUB_OUTPUT
      shell: bash

    - name: inputs-outputs
      id: inputs-outputs
      run: echo "inputs-outputs=$(echo ${{runner.os}} - ${{inputs.neofetch}} - ${{inputs.shell}} - ${{inputs.locale}} - ${{inputs.timezone}} )" >> $GITHUB_OUTPUT
      shell: bash

    - name: shell-outputs
      id: shell-outputs
      run: echo "shell-outputs=$(echo ${{inputs.shell}})" >> $GITHUB_OUTPUT
      shell: bash

    - name: comand-outputs
      id: comand-outputs
      run: echo "comand-outputs=$(echo ${{inputs.comand}})" >> $GITHUB_OUTPUT
      shell: bash

    - name: is-Linux
      id: is-Linux
      if: runner.os == 'Linux'
      run: |
       sudo locale-gen ${{ inputs.locale }}
       sudo update-locale LANG=${{ inputs.locale }}
       sudo timedatectl set-timezone ${{ inputs.timezone }}
      shell: ${{ inputs.shell }}

    - name: is-macOS
      id: is-macOS
      if: runner.os == 'macOS'
      run: |
       echo ${{ runner.os }}
       sudo systemsetup -settimezone ${{ inputs.timezone }}
       sudo systemsetup -gettimezone
       echo "export LC_CTYPE=${{ inputs.locale }}" >> $HOME/.bashrc
       echo "export LC_ALL=${{ inputs.locale }}" >> $HOME/.bashrc
       echo "export LANG=${{ inputs.locale }}" >> $HOME/.bashrc
      shell: ${{ inputs.shell }}



    - name: is-Windows
      id: is-Windows
      if: runner.os == 'Windows' && inputs.shell != 'cmd'
      run: |
       echo ${{ runner.os }}
       Set-WinSystemLocale ${{ inputs.locale }}
       Set-WinSystemLocale -SystemLocale ${{ inputs.locale }}
       Set-Culture ${{ inputs.locale }}
       Set-Culture -CultureInfo ${{ inputs.locale }}
       Set-TimeZone -Id "${{ inputs.timezone }}"
      shell: ${{ inputs.shell }}

    - name: is-Windows-cmd
      id: is-Windows-cmd
      if: inputs.shell == 'cmd'
      run: |
        tzutil /s "${{ inputs.timezone }}"
        tzutil /g
        ${{inputs.comand}}
      shell: ${{ inputs.shell }}

    - name: Neofetch
      id: Neofetch
      if: runner.os != 'Windows' && inputs.neofetch != 'false'
      run: |
       chmod +x ${{ github.action_path }}/neofetch.sh
       ${{ github.action_path }}/neofetch.sh
      shell: ${{ inputs.shell }}

    - name: Winfetch-ps1
      id: Winfetch-ps1
      if: runner.os == 'Windows' && inputs.shell != 'cmd' && inputs.neofetch != 'false'
      run: |
       ${{ github.action_path }}/winfetch.ps1
      shell: ${{ inputs.shell }}

    - name: Winfetch-bat
      id: Winfetch-bat
      if: runner.os == 'Windows' && inputs.shell == 'cmd' && inputs.neofetch != 'false'
      run: |
       ${{ github.action_path }}/winfetch.bat
      shell: ${{ inputs.shell }}