name: 'Hello World'
description: 'Greet someone'

inputs:
  actor:  # id of input
    description: 'Who to greet'
    required: false
    default: ${{ github.actor }}
  shell:  # id of input
    description: 'Use shell'
    required: false
    default: ""
  locale:  # id of input
    description: 'Use locale'
    required: false
    default: ""
  timezone:  # id of input
    description: 'Use timezone'
    required: false
    default: ""
  comand:  # id of input
    description: 'Use comand'
    required: false
    default: ""


outputs:
  inputs-outputs:
    description: "inputs-outputs"
    value: "${{ steps.inputs-outputs.outputs.inputs-outputs }}"
  shell-outputs:
    description: "shell-outputs"
    value: "${{ steps.shell-outputs.outputs.shell-outputs }}"
  comand-outputs:
    description: "comand-outputs"
    value: "${{ steps.comand-outputs.outputs.comand-outputs }}"


runs:
  using: "composite"
  steps:

    - name: inputs exists
      id: exists
      if: inputs.shell != '' && inputs.locale != '' && inputs.timezone != '' && inputs.comand != ''
      run:  |
       echo "::warning::Hey ${{ inputs.actor }}, add some inputs"
       exit
      shell: bash

    - name: inputs values
      id: values
      run: |
        echo "::group::Inputs"
        echo "Actor: ${{ inputs.timezone }}."
        echo "Shell: ${{ inputs.shell }}."
        echo "Locale: ${{ inputs.locale }}."
        echo "Timezone: ${{ inputs.timezone }}."
        echo "Comand: ${{ inputs.timezone }}."
        echo "::endgroup::"
      shell: bash

    - name: inputs-outputs
      id: inputs-outputs
      run: echo "inputs-outputs=$(echo ${{runner.os}} - ${{inputs.shell}} - ${{inputs.locale}} - ${{inputs.timezone}} )" >> $GITHUB_OUTPUT
      shell: bash

    - name: shell-outputs
      id: shell-outputs
      run: echo "shell-outputs=$(echo ${{inputs.shell}})" >> $GITHUB_OUTPUT
      shell: bash

    - name: comand-outputs
      id: comand-outputs
      run: echo "comand-outputs=$(echo ${{inputs.comand}})" >> $GITHUB_OUTPUT
      shell: bash

    - name: is-Linux
      id: is-Linux
      if: runner.os == 'Linux'
      run: |
       sudo locale-gen ${{ inputs.locale }}
       sudo update-locale LANG=${{ inputs.locale }}
       sudo timedatectl set-timezone ${{ inputs.timezone }}
       echo "LANG=$(echo ${{ inputs.locale }})" >> $GITHUB_ENV
      shell: ${{ inputs.shell }}

    - name: is-macOS
      id: is-macOS
      if: runner.os == 'macOS'
      run: |
       echo ${{ runner.os }}
       sudo systemsetup -settimezone ${{ inputs.timezone }}
       sudo systemsetup -gettimezone
       echo "export LC_CTYPE=${{ inputs.locale }}" >> $HOME/.bashrc
       echo "export LC_ALL=${{ inputs.locale }}" >> $HOME/.bashrc
       echo "export LANG=${{ inputs.locale }}" >> $HOME/.bashrc
      shell: ${{ inputs.shell }}



    - name: is-Windows
      id: is-Windows
      if: runner.os == 'Windows' && inputs.shell != 'cmd'
      run: |
       echo ${{ runner.os }}
       Set-WinSystemLocale ${{ inputs.locale }}
       Set-WinSystemLocale -SystemLocale ${{ inputs.locale }}
       Set-Culture ${{ inputs.locale }}
       Set-Culture -CultureInfo ${{ inputs.locale }}
       Set-TimeZone -Id "${{ inputs.timezone }}"
      shell: ${{ inputs.shell }}

    - name: is-Windows-cmd
      id: is-Windows-cmd
      if: inputs.shell == 'cmd'
      run: |
        tzutil /s "${{ inputs.timezone }}"
        tzutil /g
        ${{inputs.comand}}
      shell: ${{ inputs.shell }}
